### ISSUE TITLE
DanmakuParser 在 Android 9 上出现错误(ERROR)

### ISSUE THREAD

**Issue by duzhaokun123** [czp3009/bilibili-api#33]
android 版本: LineageOS 16 (android 9)
bilibili-api 版本: 0.2.0
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-15
    Process: com.duzhaokun123.bilibilihd, PID: 24430
    java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLInputFactory;
        at com.hiczp.bilibili.api.danmaku.DanmakuParser.parse(DanmakuParser.kt:75)
        at com.duzhaokun123.bilibilihd.ui.play.PlayActivity$3.run(PlayActivity.java:363)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.stream.XMLInputFactory" on path: DexPathList[[zip file "/data/app/com.duzhaokun123.bilibilihd-EWRpYYgLTKXGbRV_tVoFSQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.duzhaokun123.bilibilihd-EWRpYYgLTKXGbRV_tVoFSQ==/lib/arm64, /data/app/com.duzhaokun123.bilibilihd-EWRpYYgLTKXGbRV_tVoFSQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.hiczp.bilibili.api.danmaku.DanmakuParser.parse(DanmakuParser.kt:75) 
        at com.duzhaokun123.bilibilihd.ui.play.PlayActivity$3.run(PlayActivity.java:363) 
```

**Comment by czp3009** [comment]
Android 不自带流式 xml 解析器, 需要手动添加依赖

group: 'javax.xml.stream', name: 'stax-api'

杜兆琨 <notifications@github.com> 于2020年4月10日周五 下午12:09写道：
